version: '3'

services:
  pgdatabase:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi_0
    volumes:
      - ./nytaxidata:/var/lib/postgresql/data:rw
    networks:
      - net1

  pgdatawh:
    image: postgres:15
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi_1
    networks:
      - net1

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - net1
    depends_on:
      - pgdatabase

# DATA -----------------------------

  data_ingest_1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "trip_data_ingest.py",
              "--user=root",
              "--password=root",
              "--host=pgdatabase",  # Use the service name as the host
              "--port=5432",
              "--db=ny_taxi_0",
              "--db_tablename=yellow_taxi_trips",
              "--url=https://raw.githubusercontent.com/ryandipp/nytaxidatapipeline/main/datasets/yellowtaxitrip_0121.csv"]
    depends_on:
      - pgdatabase
    networks:
      - net1
  
  data_ingest_2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "zones_data_ingest.py",
              "--user=root",
              "--password=root",
              "--host=pgdatabase",  # Use the service name as the host
              "--port=5432",
              "--db=ny_taxi_0",
              "--db_tablename=taxi_zones",
              "--url=https://raw.githubusercontent.com/ryandipp/nytaxidatapipeline/main/datasets/taxizone.csv"]
    depends_on:
      - pgdatabase
    networks:
      - net1

  dumploadjob:
    build:
      context: ./dumpload_job
      dockerfile: Dockerfile
    command: ["python", "dump_load.py"]
    depends_on:
      - pgdatabase
      - pgdatawh
    networks:
      - net1

networks:
  net1:
    driver: bridge